Update lowercase-files.yml

diff --git a/.github/workflows/lowercase-files.yml b/.github/workflows/lowercase-files.yml
--- a/.github/workflows/lowercase-files.yml
+++ b/.github/workflows/lowercase-files.yml
@@ -39,4 +39,17 @@ jobs:
         uses: trilom/file-changes-action@v1.2.3
       - name: test
         run: |
-          cat $HOME/files_added.json
+          
+          FILES=$( cat $HOME/files_added.json )
+
+          IFS=", " read -a myarray <<< $FILES
+
+          for filename in "${myarray[@]}" 
+          do
+              pureFile=$(echo $filename | sed 's/"//g' | sed 's/]//g' | grep -o '...$')
+              if [ $pureFile == "GIF" ] || [ $pureFile == "SVG" ];
+              then
+                  echo 'FAIL FAIL FAIL FAIL FAIL FAIL'
+                  exit 1
+              fi
+          done
